[package]
authors = ["The Cloud Hypervisor Authors"]
edition.workspace = true
name = "vm-device"
rust-version.workspace = true
version = "0.1.0"

[features]
default = []
kvm = ["vfio-ioctls/kvm"]
mshv = ["vfio-ioctls/mshv"]

[dependencies]
hypervisor = { path = "../hypervisor" }
platform = { path = "../platform" }
serde = { workspace = true, features = ["derive", "rc"] }
thiserror = { workspace = true }
vm-memory = { workspace = true, features = ["backend-mmap",
] }

[target.'cfg(unix)'.dependencies]
vfio-ioctls = { workspace = true, default-features = false }
vmm-sys-util = { workspace = true }

[lints]
workspace = true
