[profile.default]
# Don't let one individual test run for more than 10 minutes
slow-timeout = { period = "60s", terminate-after = 10 }

[test-groups.metrics]
max-threads = 1

[[profile.default.overrides]]
filter = "package(performance-metrics) and test(metrics::)"
test-group = "metrics"
